# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - kakutagawa-test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_d9a5eee53a9c4fa2941bdfb02b6e85a2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9d1fcb0f119d43f2bcb55c9a8ab338a7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_d9a5eee53a9c4fa2941bdfb02b6e85a2 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kakutagawa-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_211fac87f00f4d10845bf2e183b57abf }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_d9a5eee53a9c4fa2941bdfb02b6e85a2 }}/appsvc/staticsite:${{ github.sha }}'